### ISSUE TITLE
Error in FLOW_TO_NEO4J step 

### ISSUE THREAD

**Issue by acurat** [avishek-sen-gupta/cobol-rekt#57]
First of all, thank you for the amazing toolkit. 

I am running into this error in the `FLOW_TO_NEO4J` step.  Not sure if I am doing something wrong. Help?

```[2024-11-04 13:58:06] [INFO] ACRL002.cbl -> BUILD_SEED_MODEL: OK
ACRL002.cbl -> ATTACH_COMMENTS: OK
ACRL002.cbl -> WRITE_CFG: OK
ACRL002.cbl -> DRAW_FLOWCHART: OK
ACRL002.cbl -> org.neo4j.driver.exceptions.ClientException: Unable to convert org.smojol.common.pseudocode.CodeSentinelType to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:216)
	at org.neo4j.driver.internal.util.Extract.mapOfValues(Extract.java:171)
	at org.neo4j.driver.internal.AbstractQueryRunner.parameters(AbstractQueryRunner.java:58)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37)
	at org.neo4j.driver.internal.DelegatingTransactionContext.run(DelegatingTransactionContext.java:41)
	at com.mojo.woof.WoofNode.run(WoofNode.java:29)
	at com.mojo.woof.GraphSDK.lambda$createNode$4(GraphSDK.java:76)
	at org.neo4j.driver.internal.InternalSession.lambda$execute$4(InternalSession.java:161)
	at org.neo4j.driver.internal.InternalSession.lambda$transaction$5(InternalSession.java:178)
	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:113)
	at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:175)
	at org.neo4j.driver.internal.InternalSession.execute(InternalSession.java:160)
	at org.neo4j.driver.internal.InternalSession.executeWrite(InternalSession.java:132)
	at org.neo4j.driver.Session.executeWrite(Session.java:169)
	at com.mojo.woof.GraphSDK.createNode(GraphSDK.java:75)
	at com.mojo.woof.GraphSDK.comment(GraphSDK.java:186)
	at org.smojol.toolkit.analysis.graph.neo4j.Neo4JFlowCFGVisitor.lambda$visit$0(Neo4JFlowCFGVisitor.java:23)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.smojol.toolkit.analysis.graph.neo4j.Neo4JFlowCFGVisitor.visit(Neo4JFlowCFGVisitor.java:23)
	at org.smojol.toolkit.ast.CobolFlowNode.acceptUnvisited(CobolFlowNode.java:158)
	at org.smojol.toolkit.ast.CompositeCobolFlowNode.acceptUnvisited(CompositeCobolFlowNode.java:73)
	at org.smojol.toolkit.ast.CobolFlowNode.accept(CobolFlowNode.java:149)
	at org.smojol.toolkit.analysis.task.analysis.InjectIntoNeo4JTask.exportToNeo4J(InjectIntoNeo4JTask.java:43)
	at org.smojol.toolkit.analysis.task.analysis.InjectIntoNeo4JTask.run(InjectIntoNeo4JTask.java:34)
	at org.smojol.toolkit.task.SmojolTasks$1.run(SmojolTasks.java:70)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.smojol.toolkit.task.SmojolTasks.run(SmojolTasks.java:64)
	at org.smojol.toolkit.analysis.task.analysis.CodeTaskRunner.runForProgram(CodeTaskRunner.java:154)
	at org.smojol.toolkit.analysis.task.analysis.CodeTaskRunner.runForPrograms(CodeTaskRunner.java:95)
	at org.smojol.cli.MultiCommand.processPrograms(MultiCommand.java:105)
	at org.smojol.cli.MultiCommand.call(MultiCommand.java:92)
	at org.smojol.cli.MultiCommand.call(MultiCommand.java:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.smojol.cli.MultiCommandCLI.main(MultiCommandCLI.java:10)
```

**Comment by avishek-sen-gupta** [comment]
This should be now fixed in commit [5f64681fc3718a77e1a31b0c3272363d2c5333e6](https://github.com/avishek-sen-gupta/cobol-rekt/commit/5f64681fc3718a77e1a31b0c3272363d2c5333e6). Please let me know if this fixes your issue.

**Comment by avishek-sen-gupta** [comment]
Could you open a separate issue for this please? Just for my own tracking purposes, so that I can close this issue :)

**Comment by acurat** [comment]
Sure. Original issue closed.
