### ISSUE TITLE
Summarize Through LLM Task

### ISSUE THREAD

**Issue by acurat** [avishek-sen-gupta/cobol-rekt#58]
I am primarily interested in summarizing using LLM..And currently it fails here. Can you help?

```
ACRL002.cbl -> ATTACH_COMMENTS: OK
ACRL002.cbl -> WRITE_CFG: OK
ACRL002.cbl -> DRAW_FLOWCHART: OK
ACRL002.cbl -> java.util.NoSuchElementException
	at java.base/java.util.ArrayList.getFirst(ArrayList.java:439)
	at org.smojol.toolkit.analysis.task.analysis.SummariseThroughLLMTask.summariseThroughLLM(SummariseThroughLLMTask.java:42)
	at org.smojol.toolkit.analysis.task.analysis.SummariseThroughLLMTask.run(SummariseThroughLLMTask.java:34)
	at org.smojol.toolkit.task.SmojolTasks$14.run(SmojolTasks.java:162)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.smojol.toolkit.task.SmojolTasks.run(SmojolTasks.java:64)
	at org.smojol.toolkit.analysis.task.analysis.CodeTaskRunner.runForProgram(CodeTaskRunner.java:154)
	at org.smojol.toolkit.analysis.task.analysis.CodeTaskRunner.runForPrograms(CodeTaskRunner.java:95)
	at org.smojol.cli.MultiCommand.processPrograms(MultiCommand.java:105)
	at org.smojol.cli.MultiCommand.call(MultiCommand.java:92)
	at org.smojol.cli.MultiCommand.call(MultiCommand.java:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.smojol.cli.MultiCommandCLI.main(MultiCommandCLI.java:10)

ACRL002.cbl -> WRITE_DATA_STRUCTURES: OK
```

**Comment by avishek-sen-gupta** [comment]
This should be fixed in [c4e007350eca1b15b939dd58afbda1bb8f1cce0f](https://github.com/avishek-sen-gupta/cobol-rekt/commit/c4e007350eca1b15b939dd58afbda1bb8f1cce0f). Please let me know if this works for you.

**Comment by acurat** [comment]
YOU ARE THE BEST! It worked. I will analyze the output and get back if any questions.

**Comment by acurat** [comment]
Is it possible to print the summary output (LLM responses) to the report/output folder, just like outputs for some others tasks?

**Comment by avishek-sen-gupta** [comment]
It's possible, but it would have to be a separate feature request, since this is not present in the library. Feel free to open another issue if you'd like to discuss/propose a possible feature.
Please mark this specific issue as closed if you're happy with the fix.

**Comment by acurat** [comment]
Will do. Thanks!
